server:
  port: 60003
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:60004/eureka
spring:
  application:
    name: ZuulServer
management:
  endpoints:
    web:
      exposure:
        include: routes
zuul:
  host:
    connect-timeout-millis: 15000  # 网关的连接超时要比Hystrix的大
    socket-timeout-millis: 60000   # 网关socket超时
ribbon:
  ReadTimeout: 10000               # ribbon读取超时
  ConnectTimeout: 10000            # ribbon链接超时
logging:
  config: classpath:logback.xml