server:
  port: 60004
spring:
  application:
    name: EurekaServer

eureka:
  instance:
    prefer-ip-address: true
  instance-id: 127.0.0.1:${server.port}
  client:
    fetch-registry: false
    register-with-eureka: false
